config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations'}
  get 'dashboard/index'

  resources :users do
    resources :readings
  end

  resource :dashboard, only: [:index] do
    collection do
      post :search, to: 'dashboard#search'
    end
  end

  resources :friendships, only: [:show, :create, :destroy]

  root 'dashboard#index'

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/reading.rb
class Reading < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true
  validates :author, presence: true  
  validates :reading_date, presence: true
  validates :duration_in_min, presence: true
  validates :duration_in_min, numericality: { only_integer: true }  
  validates :user_id, presence: true  

  default_scope { where("reading_date > ?", 7.days.ago).order(reading_date: :desc) }

  #how many reader to show on one page. 
  self.per_page = 3
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :readings
  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :friendships

  # Noo friends table(model)in this app & friends are also users
  # to solve this issue, add class_name: "User"
  has_many :friends, through: :friendships, class_name: "User"

  #for comments
  # has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
  
  #how many reader to show on one page. 
  self.per_page = 5
  
  def full_name
    "#{first_name} #{last_name}"        
  end   
  

  def self.search_by_name(name)
    names_array = name.split(' ')
    # names_array = name.downcase.split(' ')
    if names_array.size == 1
      where('first_name ILIKE ? or last_name ILIKE ?',
        "%#{names_array[0]}%", "%#{names_array[0]}%").order(:first_name)
    else
      where('first_name ILIKE ? or first_name ILIKE ? or last_name ILIKE ? or last_name ILIKE ?', 
    "%#{names_array[0]}%", "%#{names_array[1]}%", "%#{names_array[0]}%", "%#{names_array[1]}%").order(:first_name)
    end
  end

  def follows_or_same?(new_friend)
    friendships.map(&:friend).include?(new_friend) || self == new_friend
  end

  def current_friendship(friend)
    friendships.where(friend: friend).first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @readers = User.paginate(:page => params[:page])
  end

  def search
    @readers = User.search_by_name(params[:search_name]).paginate(:page => params[:page])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    friend = User.find(params[:friend_id])
    Friendship.create(friendship_params.merge(friend_id: params[:friend_id], 
      user_id: current_user.id)) unless current_user.follows_or_same?(friend)
    redirect_to root_path
  end

  def show
    @friend = Friendship.find(params[:id]).friend
    @logs = @friend.readings.all
  end

  def destroy
    @friendship = Friendship.find(params[:id])
    if @friendship.destroy
      flash[:success] = "#{@friendship.friend.full_name} unfollowed"
    else
      flash[:danger] = "#{@friendship.friend.full_name} could not be unfollowed"
    end
    redirect_to user_readings_path(current_user)
  end

  private
  def friendship_params
    params.permit(:friend_id, :user_id)
  end
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_reading, except: [:index, :new, :create]

  def index  
    # @reading_logs = current_user.readings.all
    @reading_logs = current_user.readings.all.paginate(:page => params[:page])
    # binding.pry
    @friends = current_user.friends
  end

  def new
    @reading_log = current_user.readings.new
  end

  def create
    @reading_log = current_user.readings.new(reading_params)

    if @reading_log.save
      flash[:success] = "Reading log has been created" 
      redirect_to [current_user, @reading_log]
    else
      flash[:danger] = "Reading Log has not been created"
      render :new
    end
  end

  def edit
  end

  def update
    if @reading_log.update(reading_params)
      flash[:success] = "Reading Log has been updated"
      redirect_to [current_user, @reading_log]
    else
      flash[:danger] = "Reading Log has not been updated"
      render :edit
    end
  end

  def show    
  end

  def destroy
    @reading_log.destroy
    flash[:success] = "Reading Log has been deleted"
    redirect_to user_readings_path(current_user)    
  end

  private
  def reading_params
    params.require(:reading).permit(:title, :author, :reading_date, :duration_in_min, :user_id, :note)
  end
  def set_reading
    @reading_log = current_user.readings.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map {
      |msg| content_tag(:li, msg) }.join
      html = <<-HTML
<div class="alert alert-error alert-danger">
  <a href='#' class='close' data-dismiss='alert'>&#215;</a>
    <%= content_tag :div, msg if msg.is_a?(String) %>
</div>
HTML
    html.html_safe
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/views/dashboard/index.html.erb
<div class="jumbotron text-center" id="main_header_img">
  <h1>Book Reading Lounge</h1>
  <p>Share your <span class="main_sub_header">Reading Log</span> with your family and friends</p>
</div>
<div>
    <h2>Little Bookworms</h2>
    <!-- <i class="fa fa-camera-retro"></i> fa-camera-retro -->
</div>
<div class="text-right">
    <%= will_paginate @readers, renderer: BootstrapPagination::Rails, class: "paginate" %>
</div>

<!-- <div class="container">
  <div class="row">
    <% @readers.each do |reader| %>
    <div class="col-md-10 well member">
      <%= reader.full_name %> 
      <% if current_user %>
        <%= link_to "Follow", friendships_path(friend_id: reader.id), method: :post, class: "btn btn-primary pull-right" unless current_user.follows_or_same?(reader) %>
      <% end %>
    </div>
    <% end %>
  </div>
</div>  -->

  <div class="row">

<% @readers.each do |reader| %>

    <div class="col-md-6">
      <div id="wrapper">
          <div class="page text-center" id="page1">
            <div class="content">
              <%= reader.full_name %>
            </div>
            <div class="follow">
              <% if current_user %>
                <%= link_to "Follow", friendships_path(friend_id: reader.id), method: :post, class: "btn btn-primary pull-right" unless current_user.follows_or_same?(reader) %>
              <% end %>
            </div>            
          </div>
          <div class="page" id="page2"><div class="content"></div></div>
          <div class="page" id="page3"><div class="content"></div></div>
          <div class="page" id="page4"><div class="content"></div></div>
          <div class="page" id="page5"><div class="content"></div></div>
          <div class="page" id="page6"><div class="content"></div></div>
          <div class="page" id="page7">
            <div class="content">
              <% if reader.readings.length >0  %>
                <% reader.readings.each do |log|  %>
                <%= log.title %>
                <br>
                <% end %>
              <% else %>
                <%= "#{reader.full_name} doesn't have a Reading Log yet" %>
              <% end %>            
            </div>
          </div>
      </div>        
    </div>
    <% end %>    
  </div>


  

app/views/dashboard/search.html.erb
<div class="container">
  <div class="row search-result">
    <% @readers.each do |reader| %>
    <div class="col-md-10 col-xs-offset-1 well member">
      <%= reader.full_name %>
      <% if current_user %>
        <%= link_to "Follow", friendships_path(friend_id: reader.id), method: :post, class: "btn btn-primary pull-right" unless current_user.follows_or_same?(reader) %>
      <% end %>      
    </div>
    <% end %>
  </div>
  <%= will_paginate @readers, renderer: BootstrapPagination::Rails %>
</div>

app/views/friendships/show.html.erb
    <p id="notice"> <%= notice %></p>
    <h1><%= @friend.full_name %>'s Reading Log</h1>

  <!--   <table class="table table-striped">
      <thead>
        <tr>
          <th>Book Title</th>
          <th>Author</th>
          <th>Reading Date</th>
          <th>Duration (min)</th>
          <th>Notes</th>
          <!-- <th colspan="3"></th> -->
      <!--   </tr>
      </thead>
      <tbody>
        <% @logs.each do |log| %>
          <tr>
            <td><%= log.title %></td>
            <td><%= log.author%></td>
            <td><%= log.reading_date %></td>
            <td><%= log.duration_in_min %></td>
            <td><%= truncate(log.note, length: 100) %></td>
          </tr>
        <% end %>      
      </tbody> -->

    <section>
      <ul class="log-list">

      <% @logs.each do |log| %>
        <li class="log<%= log.id %> ">
          <ul>
            <li><strong><%= log.title %></strong> by <%= log.author %></li>
            <li class="text-right small"><%= log.reading_date %> | <%= log.duration_in_min %> minutes</li>
            <li><hr></li>
            <li class="note"><em><%= truncate(log.note, length: 100) %></em></li>
            <li class="text-right small">
              <span class="rating" data-id="<%= log.id %>"><i class="fa fa-star icon-a"></i><i class="fa fa-star-o"></i><i class="fa fa-star" data-star="3"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i></span>
            </li>
            <li class="book-thum" data-id="<%= log.id %>" data-title="<%= log.title %>" data-author="<%= log.author %>"></li>
          </ul>
          <ul>
            <li>
              Comments: 
            </li>
          </ul>
        </li>
      <% end %>

      </ul>
    </section>

      <p>
        <%= content_tag :div, "", id: "chart", data: {logs: @logs} %>    
      </p>
      <p><%= link_to "Back", user_readings_path(current_user), class: "btn btn-primary link" %></p>

    
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Reading Log</title>
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
       <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Tangerine">
       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "partials/header" %>
    <%= render "partials/main" %>
  </body>
</html>

app/views/partials/_header.html.erb
<header role="banner">
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse"
        data-target="#bs-example-navbar-collapse-1">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Bookworm", root_path, class: "navbar-brand" %>
      </div>
      <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active">
            <%= link_to "Home", root_path %>
            <span class="sr-only">(current)</span>
          </li>
        </ul>
        <%= form_tag(search_dashboard_path, class: "navbar-form navbar-left", role: "search") do %>
        <div class="form-group">
          <%= text_field_tag :search_name, nil, placeholder: "Search for friends", class: "form-control" %>
        </div>
        <%= submit_tag "Search", class: "btn btn-default" %>
        <% end %>

        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "My Lounge", user_readings_path(current_user) %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            <div class="navbar-right">
              <p class="navbar-text"><%= "#{current_user.full_name}" %>&nbsp;&nbsp;</p>
            </div>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>          
          <% end %>  
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/partials/_main.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class='alert alert-<%= "#{name}" %>'>
      <a href="#" class='close' data-dismiss='alert'> &#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
  <% end %>
  <%= yield %>
</div>

app/views/readings/_form.html.erb
<div class='row'>
  <div class='col-md-12'>
  <%= form_for([current_user, @reading_log], :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <% if @reading_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reading_log.errors.count, "error") %>
      prohibited this reading log from being saved: </h2>
      <ul>
      <% @reading_log.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
      <div class="control-label col-md-2">
      <%= f.label :title, "Book Title" %><br>
      </div>
      <div class="col-md-10">
      <%= f.text_field :title %>
      </div>
    </div>

    <div class="form-group">
      <div class="control-label col-md-2">
      <%= f.label :author, "Author" %><br>
      </div>
      <div class="col-md-10">
      <%= f.text_field :author %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-md-2">
      <%= f.label :note, "Notes" %><br>
      </div>
      <div class="col-md-10">
      <%= f.text_area :note, class: "form-control", rows: "10" %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-md-2">
      <%= f.label :reading_date, "Reading Date" %>
      </div>
      <div class="col-md-10">
      <%= f.text_field :reading_date, class: "form-control", id: "reading_reading_date" %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-md-2">
      <%= f.label :duration_in_min, "Duration (min)" %>
      </div>
      <div class="col-md-10">
      <%= f.number_field :duration_in_min, class: "form-control" %>
      </div>
    </div>    
    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
      <%= f.submit class: "btn btn-primary btn-lg" %>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/readings/edit.html.erb
<h1 class="text-center">Editing Reading Log for <%= current_user.full_name %></h1>
<%= render "form" %>

<%= link_to "Show", [current_user, @reading_log] %>
<%= link_to "Back", user_readings_path(current_user) %>

app/views/readings/index.html.erb
<%= link_to "New Reading Log", new_user_reading_path(current_user), class: "btn btn-primary link" %>

<div class="row">
  <div class="col-md-9 col-xs-12 text-right">
    <%= will_paginate @reading_logs, renderer: BootstrapPagination::Rails, class: "paginate" %>
  </div>
</div>
<div class="row">
  <div class="col-md-9 col-xs-12">
    <% unless @reading_logs.empty? %>
    <section>
      <ul class="log-list">

      <% @reading_logs.each do |log| %>
        <li class="log<%= log.id %> ">
          <ul>
            <li><strong><%= log.title %></strong> by <%= log.author %></li>
            <li class="text-right small"><%= log.reading_date %> | <%= log.duration_in_min %> minutes</li>
            <li><hr></li>
            <li class="note"><em><%= truncate(log.note, length: 100) %></em></li> 
            <li class="text-right small">

              <%= link_to "Edit This Log", [:edit, current_user, log] %> | <%= link_to "Delete", [current_user, log], method: :delete, data: {confirm: "Are you sure?" } %>

              <span class="rating" data-id="<%= log.id %>"><i class="fa fa-star icon-a"></i><i class="fa fa-star-o"></i><i class="fa fa-star" data-star="3"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i></span>                                                    
            </li>
            <li class="book-thum" data-id="<%= log.id %>" data-title="<%= log.title %>" data-author="<%= log.author %>">
            </li>
          </ul>
        </li>
      <% end %> 

      </ul>
    </section>

    <% else %>
    <div class="alert alert-danger message-font text-center" role="alert">No Reading Log Yet</div>
    <br>
    <% end %>
    <div class="chart-box">
      <%= content_tag :div, "", id: "chart", data: {logs: @reading_logs} %>
    </div>
  </div>

  <div class="col-md-3 col-xs-12 text-center">
    <h4>My Friends</h4>
    <hr class="style-one">
    <% @friends.each do |friend| %>
      <div class="friend_name">
        <span class="fa-stack fa-lg">
          <i class="fa fa-square-o fa-stack-2x"></i>
          <i class="fa fa-user-secret fa-stack-1x"></i>
        </span>      

        <%= link_to friend.full_name, friendship_path(current_user.current_friendship(friend)) %>
     
        <%= link_to "Unfollow", friendship_path(current_user.current_friendship(friend)), method: :delete, data: {confirm: "Are you sure?"}, class: "btn-unfollow" %>

    <% end %>
  </div>
</div>

app/views/readings/new.html.erb
<h1 class="text-center">New Reading Log for <%= current_user.full_name %></h1>

<%= render 'form' %>

<div class="row">
  <div class="col-md-12">
    <div class="col-md-10 col-md-offset-2">
      <%= link_to "Back", user_readings_path(current_user), class: "btn btn-primary link", id: "new-read-btn" %>      
    </div>
  </div>
</div>

app/views/readings/show.html.erb
<div class="col-xs-12 col-md-10 col-md-offset-1">
  <div>
    <h2 class="show-header">Showing <%= "#{@reading_log.user.full_name}'s Reading Details" %></h2>
  </div>

  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Book Title:</strong>
    </div>
    <div class="col-xs-8 text-right">
      <%= @reading_log.title %>
    </div>
  </div>


  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Author:</strong>
    </div>
    <div class="col-xs-8 text-right">
      <%= @reading_log.author %>
    </div>
  </div>

  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Reading Note:</strong>
    </div>
    <div class="col-xs-8 text-right">
      <%= truncate(@reading_log.note, length: 50) %>
    </div>
  </div>

  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Reading Date:</strong>
    </div>
    <div class="col-xs-8 text-right">
      <%= @reading_log.reading_date %>
    </div>
  </div>

  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Duration (min):</strong>
    </div>
    <div class="col-xs-8 text-right">
      <%= @reading_log.duration_in_min %>
    </div>
  </div>

  <div class="col-xs-12 col-md-10 member">
    <%= link_to "Back", user_readings_path(current_user) %>
  </div>
</div>